Controllers/ScoresController.cs
/* Daniel Hinbest
 * NETD 3202 - Lab 5
 * December 6, 2020
 * This ASP.NET Core application is designed to allow the user to enter the information for a curling game, including the teams and the scores, and also provides functionality for editing, and deleting results.
 * The ScoresController generates the views for the scores tables
 */
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NETD3202_Communication5.Data;
using NETD3202_Communication5.Models;
using Microsoft.AspNetCore.Authorization;

namespace NETD3202_Communication5.Controllers
{
    public class ScoresController : Controller
    {
        // Creates a readonly instance of the ScoresContext
        private readonly ApplicationDbContext _context;

        /// <summary>
        /// Creates an instance of the ScoresController with the ScoresContext parameter
        /// </summary>
        /// <param name="context">Sets the context to the parameter</param>
        public ScoresController(ApplicationDbContext context)
        {
            _context = context;
        }

        /// <summary>
        /// Generates the Scores index view with the table in a list
        /// </summary>
        /// <returns>The Scores index view with the scores table converted to a list</returns>
        public async Task<IActionResult> Index()
        {
            // Returns the scores view in a list
            return View(await _context.Scores.ToListAsync());
        }

        /// <summary>
        /// Generates the details view with the content of the selected record
        /// </summary>
        /// <param name="id">The id of the record selected</param>
        /// <returns>Returns NotFound if invalid, otherwise the details view with the selected score</returns>
        public async Task<IActionResult> Details(int? id)
        {
            // If the ID is not set...
            if (id == null)
            {
                // Return NotFound
                return NotFound();
            }

            // Take the score content with the selected ID and store it in the score variable
            var score = await _context.Scores.FirstOrDefaultAsync(m => m.scoreID == id);

            // If the score is not set...
            if (score == null)
            {
                // Return NotFound
                return NotFound();
            }

            // Return the view with the score record
            return View(score);
        }

        /// <summary>
        /// Generates the Create view, which allows the user to create a new score record
        /// </summary>
        /// <returns>Returns the Create view</returns>
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// Records the information stored in the create view into the scores table
        /// </summary>
        /// <param name="scores">This parameter is the scores entered</param>
        /// <returns>Returns the view with the scores entered in post mode</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("scoreID,teamOneTotal,teamTwoTotal,teamOneEnds,TeamTwoEnds")] Score scores)
        {
            // If the model is valid...
            if (ModelState.IsValid)
            {
                // Add the entered scores into the context and redirect to the Index
                _context.Add(scores);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            // Return the view with the scores
            return View(scores);
        }

        /// <summary>
        /// After the user selects a record from the Scores Index, this allows the user to edit the score
        /// </summary>
        /// <param name="id">The ID of the score being altered</param>
        /// <returns>Returns the Edit view with the scores</returns>
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            // If the ID is not set...
            if (id == null)
            {
                // Return NotFound
                return NotFound();
            }

            // Find the ID of the selected score and store it in a variable
            var scores = await _context.Scores.FindAsync(id);

            // If scores is not set...
            if (scores == null)
            {
                // Return NotFound
                return NotFound();
            }

            // Return the Edit view with the scores
            return View(scores);
        }

        /// <summary>
        /// Updates the edited score from the Scores table
        /// </summary>
        /// <param name="id">The ID number of the selected score</param>
        /// <param name="scores">The content of the score</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("scoreID,teamOneTotal,teamTwoTotal,teamOneEnds,TeamTwoEnds")] Score scores)
        {
            // If the ID does not match the Score ID...
            if (id != scores.scoreID)
            {
                // Return NotFound
                return NotFound();
            }

            // If the model is valid
            if (ModelState.IsValid)
            {
                // Try/Catch exception handling
                try
                {
                    // Update the context with the new scores content
                    _context.Update(scores);
                    // Save the changes to the context
                    await _context.SaveChangesAsync();
                }
                // If a DbUpdateConcurrencyException occurs...
                catch (DbUpdateConcurrencyException)
                {
                    // If the score does not exist...
                    if (!ScoreExists(scores.scoreID))
                    {
                        // Return NotFound
                        return NotFound();
                    }
                    // If the score exists...
                    else
                    {
                        // Throw an exception
                        throw;
                    }
                }

                // Redirect back to the index
                return RedirectToAction(nameof(Index));
            }

            //Return a view with the scores
            return View(scores);
        }

        /// <summary>
        /// Deletes a record from the database
        /// </summary>
        /// <param name="id">The ID of the deleted score</param>
        /// <returns>Returns a view of the scores</returns>
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            // If the ID is null...
            if (id == null)
            {
                // Return NotFound
                return NotFound();
            }

            // Get the score from the table and store it in a variable
            var scores = await _context.Scores.FirstOrDefaultAsync(m => m.scoreID == id);

            // If the score is null...
            if (scores == null)
            {
                // Return NotFound
                return NotFound();
            }

            // Return a view of the scores
            return View(scores);
        }

        /// <summary>
        /// Deletes the selected record from the database
        /// </summary>
        /// <param name="id">The ID of the selected record</param>
        /// <returns>Returns a redirection back to the Index</returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            // Finds the record from the database with a matching ID and stores it in a variable
            var scores = await _context.Scores.FindAsync(id);

            // Removes the score from the context
            _context.Scores.Remove(scores);
            // Saves changes to the context to update the records
            await _context.SaveChangesAsync();
            // Return the user back to the Index
            return RedirectToAction(nameof(Index));
        }

        /// <summary>
        /// ScoreExists checks for the existance of the selected score
        /// </summary>
        /// <param name="id">The ID number of the score</param>
        /// <returns>Returns the result of the search</returns>
        public bool ScoreExists(int id)
        {
            // Returns the score with a matching ID
            return _context.Scores.Any(e => e.scoreID == id);
        }
    }
}

Controllers/TeamController.cs
/* Daniel Hinbest
 * NETD 3202 - Lab 5
 * December 6, 2020
 * This ASP.NET Core application is designed to allow the user to enter the information for a curling game, including the teams and the scores, and also provides functionality for editing, and deleting results.
 * This controller handles the functionality of the Teams views
 */
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NETD3202_Communication5.Models;
using NETD3202_Communication5.Data;
using Microsoft.AspNetCore.Authorization;

namespace NETD3202_Communication5.Controllers
{
    public class TeamController : Controller
    {
        // Sets a readonly variable of a ScoresContext
        private readonly ApplicationDbContext _context;

        /// <summary>
        /// Creates a new instance of the TeamController with the ScoresContext passed as a parameter
        /// </summary>
        /// <param name="context"></param>
        public TeamController(ApplicationDbContext context)
        {
            // Sets the parameter to the value of the variable
            _context = context;
        }

        /// <summary>
        /// Generates the Team Index view
        /// </summary>
        /// <returns>Returns the Teams table</returns>
        public async Task<IActionResult> Index()
        {
            // Returns the scores view into a list
            return View(await _context.Teams.ToListAsync());
        }

        /// <summary>
        /// Generates the details view with the selected record
        /// </summary>
        /// <param name="id">The ID number of the selected record</param>
        /// <returns>Returns the details view with the team if valid</returns>
        public async Task<IActionResult> Details(int? id)
        {
            // If the ID is not set...
            if (id == null)
            {
                // Return NotFound
                return NotFound();
            }

            // Store the content of the team record into a variable
            var team = await _context.Teams.FirstOrDefaultAsync(m => m.teamID == id);

            // If the team is null...
            if (team == null)
            {
                // Return NotFound
                return NotFound();
            }

            // Return the details view with the team record
            return View(team);
        }

        /// <summary>
        /// Creates a new team record
        /// </summary>
        /// <returns>Returns the Create view</returns>
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// Creates a new record from the team Create view
        /// </summary>
        /// <param name="team">The team added to the database</param>
        /// <returns>Returns the view with the team</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("scoreID,leadName,secondName,viceName,skipName")] Team team)
        {
            // If the model is valid
            if (ModelState.IsValid)
            {
                // Add the team to the context
                _context.Add(team);
                // Save the changes and update the database
                await _context.SaveChangesAsync();
                // return the Index view
                return RedirectToAction(nameof(Index));
            }
            return View(team);
        }

        /// <summary>
        /// Generates the view to edit a team
        /// </summary>
        /// <param name="id">The ID number of the team</param>
        /// <returns>Returns the view with the team content</returns>
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            // If the ID is null...
            if (id == null)
            {
                // Return NotFound
                return NotFound();
            }

            // Search the content for the team
            var team = await _context.Teams.FindAsync(id);

            // If the team is null...
            if (team == null)
            {
                // Return NotFound
                return NotFound();
            }
            // Return the Edit view with the team content
            return View(team);
        }

        /// <summary>
        /// Generates the edit view in post mode
        /// </summary>
        /// <param name="id">The ID view for the record</param>
        /// <param name="team">The team record content</param>
        /// <returns>Return the edit team record</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("scoreID,leadName,secondName,viceName,skipName")] Team team)
        {
            // If the team id does not match the parameter...
            if (id != team.teamID)
            {
                // Return NotFound
                return NotFound();
            }

            // If the model is valid...
            if (ModelState.IsValid)
            {
                // Try/Catch exception handling
                try
                {
                    // Update the context with the team content
                    _context.Update(team);
                    // Save the changes to the context
                    await _context.SaveChangesAsync();
                }
                // If a DbUpdateConcurrencyException occurs...
                catch (DbUpdateConcurrencyException)
                {
                    // If the team with the provided ID does not exist...
                    if (!TeamExists(team.teamID))
                    {
                        // Return NotFound
                        return NotFound();
                    }
                    else
                    {
                        // Otherwise throw an exception
                        throw;
                    }
                }

                // Redirect to the Index view
                return RedirectToAction(nameof(Index));
            }
            return View(team);
        }

        /// <summary>
        /// Generates the delete view to delete a record
        /// </summary>
        /// <param name="id">The ID of the record</param>
        /// <returns>Returns the view with the team content</returns>
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            // If ID is null...
            if (id == null)
            {
                //Return NotFound
                return NotFound();
            }

            // Store the team content in a variable
            var team = await _context.Teams.FirstOrDefaultAsync(m => m.teamID == id);

            // If the team is null...
            if (team == null)
            {
                // Return NotFound
                return NotFound();
            }

            // Return the delete view with the team content
            return View(team);
        }

        /// <summary>
        /// Generates the Delete view in post mode with an action to delete the record
        /// </summary>
        /// <param name="id">The ID of the selected record</param>
        /// <returns>Returns to the Index with a deleted record</returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            // Store the team from the context in a variable
            var team = await _context.Teams.FindAsync(id);
            // Remove the team from the context
            _context.Teams.Remove(team);
            // Save the changes to the context
            await _context.SaveChangesAsync();
            // Return to Index
            return RedirectToAction(nameof(Index));
        }

        /// <summary>
        /// Checks if the team exists
        /// </summary>
        /// <param name="id">The ID used to check for a team</param>
        /// <returns></returns>
        private bool TeamExists(int id)
        {
            // Return true if the team exists. If not, return false
            return _context.Teams.Any(e => e.teamID == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!--
    Daniel Hinbest
    NETD 3202 - Communication Activity 5
    December 13, 2020
    This new version now includes sign-in functionality with the Identity Framework

    This ASP.NET Core application is designed to allow the user to enter the information for a curling game, including the teams and the scores, and also provides functionality for editing, and deleting results.
    This page allows the user to view the details for an individual record.
    The template for this application is the same template provided for Web Development - Intermediate (WEBD 3201).
 -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link runat="server" rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
    <link runat="server" rel="icon" href="/favicon.ico" type="image/ico" />
    <!-- The title for the page's tab -->
    <title>@ViewData["Title"]</title>
    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="/css/styles.css" rel="stylesheet">
</head>
<body>
    @*Top navigation bar*@
    <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
        @*Logo. Redirects to the main Index*@
        <a class="navbar-brand col-sm-3 col-md-2 mr-0" asp-area="" asp-controller="Home" asp-action="Index">
            <img src="~/download.jpg" href="Index" width="50" />
            Curling Tracker
        </a>
        <!--Loads the login view-->
        @await Html.PartialAsync("_LoginPartial")
    </nav>
    <div class="container">
        <main role="main" class="pb-3">
            <div class="container-fluid">
                <div class="row">
                    <nav class="col-md-2 d-none d-md-block bg-light sidebar">
                        <div class="sidebar-sticky">
                            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                                @*Nav links for the scores table*@
                                <span>Curling Scores</span>
                                <a class="d-flex align-items-center text-muted" href="#">
                                    <span data-feather="plus-circle"></span>
                                </a>
                            </h6>
                            <ul class="nav flex-column">
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Scores" asp-action="Index">
                                        <span data-feather="home"></span>
                                        View Scores List<span class="sr-only">(current)</span>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Scores" asp-action="Create">
                                        <span data-feather="home"></span>
                                        Create New Score<span class="sr-only">(current)</span>
                                    </a>
                                </li>
                            </ul>

                            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                                @*Nav links for the teams table*@
                                <span>Curling Teams</span>
                                <a class="d-flex align-items-center text-muted" asp-area="" asp->
                                    <span data-feather="plus-circle"></span>
                                </a>
                            </h6>
                            <ul class="nav flex-column mb-2">
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Team" asp-action="Index">
                                        <span data-feather="file-text"></span>
                                        View Teams List
                                    </a>
                                </li>
                                <li class="nav flex-column mb-2">
                                    <a class="nav-link" asp-area="" asp-controller="Team" asp-action="Create">
                                        <span data-feather="file-text"></span>
                                        Create New Team
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </nav><!-- The main part of the page. This is where all page content is stored. -->
                    <main class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
                        <!--Renders the body of the pages-->
                        @RenderBody()
                    </main>
                </div>

                <footer class="border-top footer text-muted">

                    <!--Copyright symbol-->
                    <p class="mt-5 mb-3 text-muted text-center">&copy; 2020</p>
                </footer>
                <script src="~/lib/jquery/dist/jquery.min.js"></script>
                <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
                <script src="~/js/site.js" asp-append-version="true"></script>
                @RenderSection("Scripts", required: false)
            </div>
        </main>
    </div>
</body>
</html>